apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "eric-odp-factory.name" . }}-api
  namespace: {{ .Release.Namespace }}
  labels: {{- include "eric-odp-factory.labels" . | indent 4 }}
  annotations: {{- include "eric-odp-factory.annotations" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]
