apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-odp-factory.name" . }}
  labels:
    {{- include "eric-odp-factory.labels" . | indent 4 }}
  annotations:
    {{- include "eric-odp-factory.annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}